### ISSUE TITLE
Slowdown from discontinuity declaration

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DelayDiffEq.jl#120]
https://discourse.julialang.org/t/declaring-state-dependent-delay-with-ddeproblem-simulation-gets-slower/26048

It would be good to profile this a bit.

**Comment by devmotion** [comment]
I had a quick look and posted some comments.

**Comment by ChrisRackauckas** [comment]
Are we appropriately handling the type instability from the tuple of functions? I don't see why we would get so much extra allocations from the tracking, since that callback part should be non-allocating.

**Comment by devmotion** [comment]
In general, we might want to use some of the ideas from the discussion of break point detection in RADAR5: http://www.unige.ch/~hairer/preprints/break-point.pdf

It seems two major differences are that
1) breaking point detection is only run if a step is rejected AND there exists a previous breaking point `T` such that `lag(u(t), p, t) - T` changes sign in the current step
2) estimation of the breaking points is done by iteratively updating the stage values of the current step and performing root finding based on the updated dense output.

**Comment by ChrisRackauckas** [comment]
I don't know if we can do (2) with the current setup. It seems to really require implicit schemes. It would be nice to make a pure Julia RADAR5 and see how that performs though.

**Comment by devmotion** [comment]
It seems applying suggestion (1) (and another one not mentioned in the comment above) is very helpful for this problem: https://github.com/JuliaDiffEq/DelayDiffEq.jl/pull/121

**Comment by devmotion** [comment]
@AlexNascou Have you checked if your issues are fixed in the latest version of DelayDiffEq?

**Comment by AlexNascou** [comment]
Yes I tried it last night and it worked perfectly after updating all the packages. And it was only marginally slower with the dependent lags declared.
Thanks again!

**Comment by devmotion** [comment]
Great to hear, then I'll close this issue.
