### ISSUE TITLE
Slow compile times

### ISSUE THREAD

**Issue by devmotion** [JuliaDiffEq/DelayDiffEq.jl#125]
While benchmarking some DDE algorithms I noticed almost unbearable compile times (see https://github.com/JuliaDiffEq/DiffEqDevTools.jl/issues/42).

I just copied the example from that issue to a file "benchmark.jl"
```julia
using DelayDiffEq, DiffEqDevTools, DiffEqProblemLibrary.DDEProblemLibrary
DDEProblemLibrary.importddeproblems()

const prob = DDEProblemLibrary.prob_dde_mackey
const sol = solve(prob, MethodOfSteps(Vern9()); dtmax = 0.1, reltol = 1e-14, abstol = 1e-14)
const test_sol = TestSolution(sol)

function test(alg, abstols, reltols)
    @time WorkPrecisionSet(prob, abstols, reltols, [Dict(:alg => MethodOfSteps(alg))];
                           appxsol = test_sol, maxiters = 100_000, error_estimate = :final)

    @time WorkPrecisionSet(prob, abstols, reltols, [Dict(:alg => MethodOfSteps(alg))];
                           appxsol = test_sol, maxiters = 100_000, error_estimate = :final)

    nothing
end

test(BS3(), [1e-4, 1e-5], [1e-1, 1e-2])
```
and ran
```
julia --project=. --startup-file=no -e "include(\"benchmark.jl\")"
```
for different versions of `DelayDiffEq`, `OrdinaryDiffEq`, `DiffEqBase`, `DiffEqDevTools`, and `DiffEqProblemLibrary` (using Julia 1.1.1).

With versions
- DelayDiffEq 5.2.0
- OrdinaryDiffEq 5.6.0
- DiffEqBase 5.7.0
- DiffEqDevTools 2.8.0
- DiffEqProblemLibrary 4.1.0
- DiffEqMonteCarlo 0.14.0

(basically, the versions from beginning of May that were use in the Mackey and Glass benchmarks http://juliadiffeq.org/DiffEqBenchmarks.jl/html/NonStiffDDE/Mackey_Glass_wpd.html), I get
```
 31.279454 seconds (210.32 M allocations: 20.587 GiB, 11.69% gc time)
 12.358761 seconds (153.44 M allocations: 2.817 GiB, 15.91% gc time)
```

However, with
- DelayDiffEq master
- OrdinaryDiffEq master
- DiffEqBase master
- DiffEqDevTools master
- DiffEqProblemLibrary master

the timings are
```
167.584735 seconds (244.37 M allocations: 93.351 GiB, 9.82% gc time)
  0.419306 seconds (1.06 M allocations: 21.572 MiB, 3.71% gc time)
```

**Comment by ChrisRackauckas** [comment]
Is it mostly Vern9?

**Comment by devmotion** [comment]
The problem is not new. With
- DelayDiffEq 5.4.1
- OrdinaryDiffEq 5.8.1
- DiffEqBase 5.10.3
- DiffEqDevTools 2.9.0
- DiffEqMonteCarlo 0.14.0

(roughly 20 days ago) I get
```julia
160.435743 seconds (221.02 M allocations: 81.873 GiB, 8.79% gc time)
  0.156057 seconds (1.32 M allocations: 24.280 MiB, 9.76% gc time)
```
Multiple runs produce slightly different numbers (sometimes also slower than on master), but the same issue seems to be present in this configuration as well.

> Is it mostly Vern9?

I only measure `BS3` in this script, `Vern9` is only used to compute an approximate solution.

**Comment by ChrisRackauckas** [comment]
Was it the introduction of `@..`?

**Comment by devmotion** [comment]
No, does not seem to be the case. Using
- DelayDiffEq 5.2.0
- OrdinaryDiffEq 5.6.1
- DiffEqBase 5.8.0
- DiffEqDevTools 2.8.0
- DiffEqProblemLibrary 4.1.0
- DiffEqMonteCarlo 0.14.0

(with `calculate_residuals` moved to DiffEqBase which uses `@..`) gives
```
 33.210539 seconds (204.77 M allocations: 20.490 GiB, 12.65% gc time)
 12.239943 seconds (152.93 M allocations: 2.808 GiB, 15.72% gc time)
```

**Comment by devmotion** [comment]
A much stronger impact has the removal of BenchmarkTools from DiffEqDevTools. With
- DelayDiffEq 5.2.0
- OrdinaryDiffEq 5.6.0
- DiffEqBase 5.7.0
- DiffEqDevTools 2.9.0
- DiffEqProblemLibrary 4.1.0
- DiffEqMonteCarlo 0.14.0
I get
```
 55.918532 seconds (134.95 M allocations: 47.677 GiB, 9.38% gc time)
  0.153114 seconds (1.32 M allocations: 24.550 MiB, 15.23% gc time)
```
This is still better than what I observe on the current master branches, but a huge change compared with DiffEqDevTools 2.8.0.

**Comment by ChrisRackauckas** [comment]
DiffEqDevTools wasn't computing correctly with BenchmarkTools because of the fancy compiler tricks it was doing, so I'm not sure that's a real effect.

**Comment by devmotion** [comment]
I think we're talking about different things, the times are not the benchmark results but (on purpose) include the compile time. When I ran the Mackey and Glass benchmarks yesterday, the results looked very similar to the ones that are available online (I haven't compared them in detail due to https://github.com/JuliaDiffEq/DiffEqDevTools.jl/issues/42, but that's fixed now). However, it took a lot of time to run those benchmarks just due to the initial compile time, and together with what we observed in https://github.com/JuliaDiffEq/DelayDiffEq.jl/pull/124#issuecomment-511368931, I was worried that we might have introduced some severe regressions regarding compilation times.

However, it seems that already the update from DiffEqDevTools 2.8.0 to 2.9.0 (including the removal of BenchmarkTools) led to an increased initial compile time and the current state is similar to how it was almost a month ago, before I started working on DelayDiffEq.

**Comment by devmotion** [comment]
My assumption is that the long compilation times that we observe could also be caused by the complicated setup of the cache using generating functions...

What makes this whole setup a bit complicated is that for some algorithms the type of the cache depends on `f` (all those with a non-linear solver, e.g.).

However, in principle the solution with the dense history and the ODE integrator would need only a very reduced cache with the tableaus to be able to perform all interpolations, it seems. Executing `addsteps!` before interpolating/extrapolating the history and the ODE integrator does not change the stages since they are already complete all the time. We have to ensure this because otherwise it can happen that the computation of an additional stage requires the evaluation of the history function at a time point in the same integration step, which in turn then calls the same `addsteps!` method, and so on... That actually happened quite commonly when using the Verner methods in the beginning and took me some time to figure out.

So, both the dense history and the ODE integrator use the cache only for dispatching to the correct interpolation and to access the correct tableau - they never call `f` or change any stages. So I'm wondering whether we could somehow call into the interpolation machinery in OrdinaryDiffEq by just using the supertype of the cache and the tableau, hoping that we can get rid of all dependencies on `f` and all unneeded types and objects.

**Comment by devmotion** [comment]
I asked for help regarding those extreme compilation times: https://discourse.julialang.org/t/extremely-long-compilation-time-2000-sec-on-win32/26496/1

**Comment by devmotion** [comment]
Avoided for now by making Zygote an optional dependence of SparseDiffTools.
