### ISSUE TITLE
Test Rosenbrock methods on RADAR5_waltman

### ISSUE THREAD

**Issue by YingboMa** [JuliaDiffEq/DelayDiffEq.jl#157]
Ref: https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/941

**Comment by ChrisRackauckas** [comment]
@devmotion can you write a test for this? I don't know what I am looking for in this example, but we should have some form of regression test here.

**Comment by devmotion** [comment]
Sure, I can add some tests, but maybe it would be useful to tag a new OrdinaryDiffEq release first?

**Comment by ChrisRackauckas** [comment]
The tag should've been released already.

**Comment by devmotion** [comment]
Hmm according to https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/releases the latest release is 5.17.1 which was tagged 9 days ago.

**Comment by ChrisRackauckas** [comment]
Oh, I incremented Project.toml but forgot to release
