### ISSUE TITLE
MethodError at early times

### ISSUE THREAD

**Issue by pwstokes225** [JuliaDiffEq/DelayDiffEq.jl#40]
I receive a MethodError when trying to solve the following DDE problem:
`DDEProblem((t,u,h,du) -> du[1] = -h(t/2)[1], t -> [1.0], [1.0], (0.0, 10.0), [])`

The error only occurs if tspan starts sufficiently early.
e.g. It works when tspan = (0.1,10.0), but not when tspan = (0.001,10.0).

**Comment by devmotion** [comment]
Thanks for bringing this up! Extrapolations at the initial time point should have been handled by https://github.com/JuliaDiffEq/DelayDiffEq.jl/blob/master/src/history_function.jl#L39, but apparently this does not work (at least not when calculating the initial time step...). Moreover, there is a type in this line (`constant_extrapolation` should rather be `constant_extrapolant`).

I fixed these issues in branch https://github.com/devmotion/DelayDiffEq.jl/tree/fix_constant_extrapolation. With these changes I could successfully solve your DDE problem.

**Comment by pwstokes225** [comment]
I can also confirm this has fixed it. Thanks!
