### ISSUE TITLE
Addition of higher order discontinuities to mesh required

### ISSUE THREAD

**Issue by devmotion** [JuliaDiffEq/DelayDiffEq.jl#41]
I'm just writing an introduction to numerical algorithms for DDE solving for my master's thesis, and therefore I'm studying Bellen and Zennaro, Numerical Methods for Delay Differential Equations. In my opinion we have to include additional discontinuities in the mesh in order to guarantee global order ``min{p,q+1}`` of the resulting DDE method where ``p`` is the order of the underlying ODE method and ``q`` the order of continuous extension, i.e. interpolant.

In `DelayDiffEq` a discontinuity of order ``k`` is defined as jump discontinuity in the ``k``th derivative of the solution to the DDE, following Shampine and Thompson, Numerical Solution of Delay Differential Equations. According to Definition 2.1.3 by Bellen and Zennaro
> A discontinuity point ``ξ`` is said to be of order ``k`` if ``y^{(s)}(ξ)`` exists for ``s = 0,...,k`` and ``y^{(k)}(ξ)`` is Lipschitz continuous at ``ξ``

which is, in my opinion, not well-defined; but it is clarified in Bellen et al., Recent trends in numerical solution of retarded functional differential equations, Acta numerica 2009:
> Every point where some derivative ``y^{(s)}`` jumps will be called discontinuity point or breaking point. We also say that a breaking point ``ξ`` has order ``k`` if the solution is ``C^k``-continuous at ``ξ``. In particular, by ``k = -1`` we mean that the solution is discontinuous at ``ξ``.

 As stressed in both publications by Bellen,
> for a method to be of order ``p``, we usually ask the solution to be at least ``C^{p+1}``-continuous on ``[t_n, t_{n+1}]``. Therefore, for the success of the method, it is crucial to include among the mesh points all discontinuities of ``y^{(s)}`` at least for ``s = 0,1,..., p+1``.

Indeed, proofs of convergence results for all algorithms (for constant delays, time dependent delays, and state dependent delays) require the solution between two adjacent mesh points to be at least ``C^{p+1}``-continuous, assuming the applied ODE method is of order ``p``. However, because of the different definition of order of discontinuities, the algorithms and theorems by Bellen et al. require "only" the addition of discontinuities up to order ``p`` to the mesh - although with our and Shampine's definition one has to include discontinuities up to order ``p+1``.

Thus I guess, the current implementation of discontinuity tracking needs to be fixed and we also have to add discontinuities in the ``p+1``th derivative to the mesh. I added a fix in https://github.com/devmotion/DelayDiffEq.jl/tree/additional_discontinuities, which also needs some tests to be adjusted.

**Comment by ChrisRackauckas** [comment]
If I'm reading this correctly the issue is that we need to keep them for one more order?

**Comment by devmotion** [comment]
Exactly.
