### ISSUE TITLE
Calculation of dt after initialization

### ISSUE THREAD

**Issue by devmotion** [JuliaDiffEq/DelayDiffEq.jl#47]
I guess we should move the calculation of `dt` after the initialization of callbacks, just as in https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/commit/3cadf5b90f048a15b7148f031eae6125f42e8860.

However, since (also in OrdinaryDiffEq!) there are some assignments based on `dt` (such as `dtcache` and `dtproposed`) prior to this calculation - should we update them? Also the cache and the linked cache in DelayDiffEq are created with the "old" `dt` value - most of the caches do not actually use `dt` but in
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/caches/linear_nonlinear_caches.jl
`expA = expm(A, dt)` has to be recalculated I guess? So these considerations not only affect DelayDiffEq but also OrdinaryDiffEq.

**Comment by ChrisRackauckas** [comment]
Master for Ordinary/Stochastic/Delay already did this change. `dtcache` is only used for fixed timesteps, and the caches that use `dt` are only fixed as well (because they stash something based on `dt`) so I don't believe the is an issue. `dtproposed` gets overwritten before it's used.

**Comment by devmotion** [comment]
> Master for Ordinary/Stochastic/Delay already did this change

But I can't see this change in DelayDiffEq... But it seems moving https://github.com/JuliaDiffEq/DelayDiffEq.jl/blob/master/src/solve.jl#L122-L135 down is the only change that is required.

**Comment by ChrisRackauckas** [comment]
Oh I thought handling it just from OrdinaryDiffEq was all that was required since that's what sets dt. This might need a fix like you mention. I only tested it well on ODEs and SDEs, and haven't added unit tests yet. Tests on DDEs will probably show that needs to be moved...

**Comment by ChrisRackauckas** [comment]
This is being addressed in https://github.com/JuliaDiffEq/DelayDiffEq.jl/pull/49, but just doubles the calculation.

**Comment by ChrisRackauckas** [comment]
Handled by https://github.com/JuliaDiffEq/DelayDiffEq.jl/pull/53
