### ISSUE TITLE
CompositeAlgorithm and switching compatibility

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DelayDiffEq.jl#64]
This library is almost compatible with the CompositeAlgorithm. The issue is just the return. The solution of the `integrator.integrator` is appropriately the `CompositeSolution`, but the `integrator`'s solution is just an `ODESolution`. The former is required because it has the `alg_choice` field which makes the interpolant match the chosen algorithm.

**Comment by devmotion** [comment]
I updated the type of the returned solution and added some tests in https://github.com/JuliaDiffEq/DelayDiffEq.jl/tree/composite. However, something seems to be incorrect/broken as the following example of the first Robertson problem in https://github.com/JuliaDiffEq/DelayDiffEq.jl/issues/67 shows:
```julia
sol = solve(prob_dde_rober1, MethodOfSteps(AutoTsit5(Rosenbrock23())); initial_order = 1)

all(sol.alg_choice .== 1)

plot(sol)
```
![newplot](https://user-images.githubusercontent.com/26102/38771606-588ce59e-4026-11e8-8bf5-703e3d2ad5bf.png)

**Comment by ChrisRackauckas** [comment]
If you check the solution, at the end the current algorithm should be `2`, but `all(sol.alg_choice .== 1)` is true, so the interpolant is broken since it's using the wrong interpolation.

**Comment by ChrisRackauckas** [comment]
@YingboMa letting you know this is working

**Comment by ChrisRackauckas** [comment]
Is the branch missing anything or is it ready to merge? LGTM?

**Comment by devmotion** [comment]
No, I guess it's complete and ready to merge. Thanks for the fix!

**Comment by ChrisRackauckas** [comment]
Thank you too. Good team effort 👍
