### ISSUE TITLE
No refactorization of Jacobian option

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DelayDiffEq.jl#7]
Stiff methods need to solve a linear system. `Rosenbrock23` would be a great method for delay diffeqs, but currently it refactorizes the Jacobian with each step. This is only a problem when doing the Picard iterations (max dt too large). But it's simple to fix because the linear solvers already have a flag for whether to change the Jacobian: it just needs to be flipped.

**Comment by ChrisRackauckas** [comment]
We should make a move on this because it should be pretty easy and would greatly speed up solving stiff DDEs. 

```julia
perform_step!(integrator,cache::ImplicitEulerConstantCache,f=integrator.f)
```

The `f=integrator.f` is a relic of the past before the nested integrators approach to DelayDiffEq.jl when I instead thought to just pass the closure `f` to make it the ODE method (that had many many failures haha which is why it no longer exists). @devmotion have you seen anywhere that still makes use of it? If not, we could instead do:

```julia
perform_step!(integrator,cache::ImplicitEulerConstantCache,repeat_step=false)
```

for if it's a repeat step. Then in the SDIRK methods, we can skip the Jacobian re-calculations by doing

```julia
if !repeat_step && cache.newton_iters == 1 && cache.ηold < 1e-3
```

and skip the `W` recalculation using

```julia
if !repeat_step && (integrator.iter < 1 || new_jac || abs(dt - (t-integrator.tprev)) > 100eps())
```

Similarly, in the Rosenbrock methods we'd do

```julia
if has_tgrad(f) && !repeat_step
```

and we'd have to change this block

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/integrators/rosenbrock_integrators.jl#L42

to pull out the linear solver part to be right after, and flag the whole thing with `if !repeat_step`.

So this will all work if we can make use of that optional argument spot. So let me know @devmotion if you've seen it in use anywhere and if not that's the go-ahead for this to get finished and finalize the stiff DDE solvers.

**Comment by devmotion** [comment]
No, I haven't seen the optional argument in the `perform_step!` in use anywhere. I guess we then just remove the optional argument from any `perform_step!` except of the SDIRK and Rosenbrock methods (which get this different optional argument), since these other methods behave the same regardless whether it's a repeated step or not? Of course, then we have to filter the type of integrators inside the fixed point iterations which is a bit ugly... Maybe we could introduce an abstract type of integrators that act differently if the step is repeated and just make those SDIRK and Rosenbrock methods are subtype of this abstract type?

**Comment by ChrisRackauckas** [comment]
I think we do an optional argument on all of them for now. Then in the future make it a keyword argument on `perform_step!`. However, we shouldn't do that now because keyword args are very slow in Julia right now, but will be fixed soon with the NamedTuples update. When that happens, we can migrate that over to keyword args with most `perform_step!` just splatting kwargs and we'll be in a good spot.

**Comment by devmotion** [comment]
Good, then I'll add it to all of them and try to apply the proposed changes in the SDIRK and Rosenbrock methods.

**Comment by devmotion** [comment]
Oh I just discovered that `initialize!` has the same optional argument. Do you know if it is needed anywhere or can we get rid of it? It is used in https://github.com/JuliaDiffEq/DelayDiffEq.jl/blob/master/src/integrator_interface.jl#L166 but we can just remove it there.

**Comment by ChrisRackauckas** [comment]
We can get rid of it there.

**Comment by devmotion** [comment]
Can this be closed?

**Comment by ChrisRackauckas** [comment]
Yup.
