### ISSUE TITLE
Instability when integrating backwards

### ISSUE THREAD

**Issue by pwstokes225** [JuliaDiffEq/DelayDiffEq.jl#82]
The following bails with an instability warning:
```
using DelayDiffEq
f(du,u,h,p,t) = du .= h(p,t+1)
sol = solve(DDEProblem(f,[1.0],(p,t)->[1.0],(1.0,0.0)),MethodOfSteps(RK4()))
```

The solution expected here is the straight line u(t) = t.

**Comment by ChrisRackauckas** [comment]
Thanks for the report. Likely `tdir` isn't getting passed down correctly.

**Comment by devmotion** [comment]
I got this example working on my computer, the main issue were lines like https://github.com/JuliaDiffEq/DelayDiffEq.jl/blob/master/src/history_function.jl#L19 which do not respect `tdir`. I'm too tired right now but I'll add some tests and open a PR in the next days.
