### ISSUE TITLE
Test failures of lazy interpolants

### ISSUE THREAD

**Issue by devmotion** [JuliaDiffEq/DelayDiffEq.jl#97]
Currently some of the tests for Vern6 and Vern9 fail sometimes (see https://travis-ci.org/JuliaDiffEq/DelayDiffEq.jl/builds). However, the test failures do not depend on the Julia version (they both fail and succeed on Julia 1.0.3 and the nightlies from time to time).

Closer inspection reveals that tests only error when tested on `Intel(R) Xeon(R) CPU @ 2.30GHz` with `libLLVM-6.0.1 (ORCJIT, haswell)` but run without problems on `Intel(R) Xeon(R) CPU @ 2.50GHz` with `libLLVM-6.0.0 (ORCJIT, ivybridge)` and `Intel(R) Xeon(R) CPU @ 2.60GHz` with `libLLVM-6.0.0 (ORCJIT, sandybridge)`. So it seems most likely the problems are caused by some floating point differences in the in-place and not in-place implementations of Vern6 and Vern9 that become apparent on specific architectures and maybe are related to https://github.com/JuliaDiffEq/DelayDiffEq.jl/issues/73.

**Comment by ChrisRackauckas** [comment]
That's pointing to a difference in compiler optimization, especially since muladd is used.
